// Code generated by MockGen. DO NOT EDIT.
// Source: redis_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/seregaa020292/capitalhub/internal/models"
)

// MockRedisRepository is a mock of RedisRepository interface.
type MockRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRepositoryMockRecorder
}

// MockRedisRepositoryMockRecorder is the mock recorder for MockRedisRepository.
type MockRedisRepositoryMockRecorder struct {
	mock *MockRedisRepository
}

// NewMockRedisRepository creates a new mock instance.
func NewMockRedisRepository(ctrl *gomock.Controller) *MockRedisRepository {
	mock := &MockRedisRepository{ctrl: ctrl}
	mock.recorder = &MockRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRepository) EXPECT() *MockRedisRepositoryMockRecorder {
	return m.recorder
}

// DeleteMarketCtx mocks base method.
func (m *MockRedisRepository) DeleteMarketCtx(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMarketCtx", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMarketCtx indicates an expected call of DeleteMarketCtx.
func (mr *MockRedisRepositoryMockRecorder) DeleteMarketCtx(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMarketCtx", reflect.TypeOf((*MockRedisRepository)(nil).DeleteMarketCtx), ctx, key)
}

// GetMarketByIDCtx mocks base method.
func (m *MockRedisRepository) GetMarketByIDCtx(ctx context.Context, key string) (*models.MarketBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketByIDCtx", ctx, key)
	ret0, _ := ret[0].(*models.MarketBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketByIDCtx indicates an expected call of GetMarketByIDCtx.
func (mr *MockRedisRepositoryMockRecorder) GetMarketByIDCtx(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketByIDCtx", reflect.TypeOf((*MockRedisRepository)(nil).GetMarketByIDCtx), ctx, key)
}

// SetMarketCtx mocks base method.
func (m *MockRedisRepository) SetMarketCtx(ctx context.Context, key string, seconds int, asset *models.MarketBase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMarketCtx", ctx, key, seconds, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMarketCtx indicates an expected call of SetMarketCtx.
func (mr *MockRedisRepositoryMockRecorder) SetMarketCtx(ctx, key, seconds, asset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMarketCtx", reflect.TypeOf((*MockRedisRepository)(nil).SetMarketCtx), ctx, key, seconds, asset)
}
